[package]
name = "lang"
version = "0.1.0"
authors = [
    "Alex Koz. <alexanderkozlovskii@wings.ai>",
    "Dm. Yakushev <dmitryyakushev@wings.ai>",
    "Maxim Kurnikov <maximkurnikov@wings.ai>"
]
edition = "2018"
publish = false

[dependencies]
libra = { package = "dfibra", git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
move-core-types = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
move-lang = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
vm = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
move-vm-types = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
libra-move-core-types = { package = "move-core-types", git = "https://github.com/dfinance/libra.git", branch = "master" }
lcs = { package = "libra-canonical-serialization", git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
vm-genesis = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
move-ir-types = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }

disassembler = { path = "disassembler" }
compat = { path = "compat", package = "move-compat"}

serde = "1.0.106"
serde_derive = "1.0.106"
serde_json = "1.0.52"
log = "0.4"
env_logger = "0.7.1"
anyhow = "1.0.28"
rand = "0.7.3"
hex = "0.4.2"
itertools = "0.9.0"
walkdir = "2.3.1"

lsp-types = {version = "0.74.0", features = ["proposed"]}
codespan = "0.8.0"
codespan-reporting = "0.8.0"
codespan9 = { package = "codespan", version = "0.9.2" }
codespan-reporting9 = { package = "codespan-reporting", version = "0.9.2" }


# bech32 support
regex = "1.3.7"
lazy_static = "1.4.0"
bech32 = "0.7.2"

[dev-dependencies]
include_dir = "0.6.0"

