[package]
name = "move-resource-viewer"
version = "0.1.1"
authors = ["Alex Koz. <a@koz.email>"]
edition = "2018"


[dependencies]
log = "0.4"
anyhow = { version = "1.0", default-features = false }

http = "0.2"
reqwest = { version = "0.10", features = ["blocking", "json"] }

serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
schemars = { version = "0.8", features = ["default", "derive", "preserve_order"] }
hex = "0.4.2"

# move-lang deps:
libra = { package = "dfibra", git = "https://github.com/dfinance/libra.git", branch = "release-1.0" }
rv = { git = "https://github.com/dfinance/libra.git", branch = "release-1.0", package = "resource-viewer" }

lang = { path = "../lang" }
git-hash = { path = "../common/git-hash" }
compat = { path = "../lang/compat", package = "move-compat"}
dnclient = { path = "../common/dnode-rest-client", package = "dnode-rest-client" }

# cli:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
anyhow = { version = "1.0", default-features = true }
clap = { version = "3.0.0-beta.2", features = [ "default", "suggestions", "color" ] }
env_logger = "0.8.2"
