name: Build Release Tools
on:
  workflow_run:
    workflows: [Create Release Page]
    types: [completed]

env:
  RUSTFLAGS: -D warnings
  CARGO_INCREMENTAL: 0
  RUSTUP_MAX_RETRIES: 10
  CARGO_NET_RETRY: 10

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: get release url
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          run_id: ${{ github.event.workflow_run.id }}
          name: release assets url
      - name: read release url
        id: release
        run: echo ::set-output name=upload_url::$(cat release-upload.url)
    outputs:
      upload_url: ${{ steps.release.outputs.upload_url }}

  build:
    runs-on: ${{ matrix.os }}
    needs: release

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
          - os: macos-latest
            platform: mac
          - os: windows-latest
            platform: win

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Build all executables
        run: cargo build --release --all --bins

      - id: mls
        name: get version of move-language-server
        uses: ./.github/actions/crate-version
        with: { crate: move-language-server }

      - id: movec
        name: get version of movec
        uses: ./.github/actions/crate-version
        with: { crate: movec }

      - id: executor
        name: get version of move-executor
        uses: ./.github/actions/crate-version
        with: { crate: move-executor }

      - id: disassembler
        name: get version of disassembler
        uses: ./.github/actions/crate-version
        with: { crate: disassembler }

      - if: ${{ matrix.platform == 'win' }}
        name: set up standard executable ext for ${{ matrix.platform }}
        run: |
          echo "OS_BIN_EXT=.exe" >> $GITHUB_ENV
          echo "::set-env name=OS_BIN_EXT::.exe"

      - name: rename some executables
        id: artifact
        run: |
          ARCH="$(uname -m)"
          RELEASE_DIR=./target/release
          MLS_NAME=move-language-server-${{ steps.mls.outputs.version }}-${{ matrix.platform }}-$ARCH$OS_BIN_EXT
          MOVEC_NAME=movec-${{ steps.movec.outputs.version }}-${{ matrix.platform }}-$ARCH$OS_BIN_EXT
          EXECUTOR_NAME=move-executor-${{ steps.executor.outputs.version }}-${{ matrix.platform }}-$ARCH$OS_BIN_EXT
          TESTRUNNER_NAME=move-testrunner-${{ steps.executor.outputs.version }}-${{ matrix.platform }}-$ARCH$OS_BIN_EXT
          DISASSEMBLER_NAME=move-disassembler-${{ steps.disassembler.outputs.version }}-${{ matrix.platform }}-$ARCH$OS_BIN_EXT
          cd $RELEASE_DIR
          ls
          mv executor_cli$OS_BIN_EXT $EXECUTOR_NAME
          mv testrunner$OS_BIN_EXT $TESTRUNNER_NAME
          mv disassembler$OS_BIN_EXT $DISASSEMBLER_NAME
          mv move-language-server$OS_BIN_EXT $MLS_NAME
          mv movec$OS_BIN_EXT $MOVEC_NAME
          ls
          echo "::set-output name=mls::$MLS_NAME"
          echo "::set-output name=movec::$MOVEC_NAME"
          echo "::set-output name=executor::$EXECUTOR_NAME"
          echo "::set-output name=testrunner::$TESTRUNNER_NAME"
          echo "::set-output name=disassembler::$DISASSEMBLER_NAME"
          echo "::set-output name=mls_path::$RELEASE_DIR/$MLS_NAME"
          echo "::set-output name=movec_path::$RELEASE_DIR/$MOVEC_NAME"
          echo "::set-output name=executor_path::$RELEASE_DIR/$EXECUTOR_NAME"
          echo "::set-output name=testrunner_path::$RELEASE_DIR/$TESTRUNNER_NAME"
          echo "::set-output name=disassembler_path::$RELEASE_DIR/$DISASSEMBLER_NAME"

      - name: Upload MLS
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ steps.artifact.outputs.mls_path }}
          asset_name: ${{ steps.artifact.outputs.mls }}
          asset_content_type: application/gzip

      - name: Upload Movec
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ steps.artifact.outputs.movec_path }}
          asset_name: ${{ steps.artifact.outputs.movec }}
          asset_content_type: application/gzip

      - name: Upload Executor
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ steps.artifact.outputs.executor_path }}
          asset_name: ${{ steps.artifact.outputs.executor }}
          asset_content_type: application/gzip

      - name: Upload TestRunner
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ steps.artifact.outputs.testrunner_path }}
          asset_name: ${{ steps.artifact.outputs.testrunner }}
          asset_content_type: application/gzip

      - name: Upload Disassembler
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ${{ steps.artifact.outputs.disassembler_path }}
          asset_name: ${{ steps.artifact.outputs.disassembler }}
          asset_content_type: application/gzip
